/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/lazy-element';
const styles_LazyVirtualComponent:any[] = ([] as any[]);
export const RenderType_LazyVirtualComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_LazyVirtualComponent,data:{}});
export function View_LazyVirtualComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',[['class',
      'virtual-element']],(null as any),(null as any),(null as any),(null as any),
      (null as any)))],(null as any),(null as any));
}
export function View_LazyVirtualComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-virtual-lazyload-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_LazyVirtualComponent_0,
      RenderType_LazyVirtualComponent)),i0.ɵdid(49152,(null as any),0,i1.LazyVirtualComponent,
      [i0.ElementRef],(null as any),(null as any))],(null as any),(null as any));
}
export const LazyVirtualComponentNgFactory:i0.ComponentFactory<i1.LazyVirtualComponent> = i0.ɵccf('app-virtual-lazyload-component',
    i1.LazyVirtualComponent,View_LazyVirtualComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcmFkaWNhdGUvRGV2ZWxvcG1lbnQvTGF6eUxvYWRpbmcvc3JjL2xhenktZWxlbWVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3JhZGljYXRlL0RldmVsb3BtZW50L0xhenlMb2FkaW5nL3NyYy9sYXp5LWVsZW1lbnQudHMiLCJuZzovLy9ob21lL3JhZGljYXRlL0RldmVsb3BtZW50L0xhenlMb2FkaW5nL3NyYy9sYXp5LWVsZW1lbnQudHMuTGF6eVZpcnR1YWxDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvcmFkaWNhdGUvRGV2ZWxvcG1lbnQvTGF6eUxvYWRpbmcvc3JjL2xhenktZWxlbWVudC50cy5MYXp5VmlydHVhbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9J3ZpcnR1YWwtZWxlbWVudCc+PC9kaXY+IiwiPGFwcC12aXJ0dWFsLWxhenlsb2FkLWNvbXBvbmVudD48L2FwcC12aXJ0dWFsLWxhenlsb2FkLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQUE7OztvQkNBQTtNQUFBO3FDQUFBLFVBQUE7TUFBQTs7OyJ9
