/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/lazy.module';
import * as i2 from './lazy-element.ngfactory';
export const LazyModuleNgFactory:i0.NgModuleFactory<i1.LazyModule> = i0.ɵcmf(i1.LazyModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.LazyVirtualComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(512,i1.LazyModule,i1.LazyModule,([] as any[])),
          i0.ɵmpd(256,'windowObject',(undefined as any),([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcmFkaWNhdGUvRGV2ZWxvcG1lbnQvTGF6eUxvYWRpbmcvc3JjL2xhenkubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvcmFkaWNhdGUvRGV2ZWxvcG1lbnQvTGF6eUxvYWRpbmcvc3JjL2xhenkubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
