/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/lazy-child.directive';
const styles_LazyVirtualComponent:any[] = ([] as any[]);
export const RenderType_LazyVirtualComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_LazyVirtualComponent,data:{}});
export function View_LazyVirtualComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',[['class',
      'virtual-element']],(null as any),(null as any),(null as any),(null as any),
      (null as any)))],(null as any),(null as any));
}
export function View_LazyVirtualComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-virtual-lazyload-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_LazyVirtualComponent_0,
      RenderType_LazyVirtualComponent)),i0.ɵdid(49152,(null as any),0,i1.LazyVirtualComponent,
      [i0.ElementRef],(null as any),(null as any))],(null as any),(null as any));
}
export const LazyVirtualComponentNgFactory:i0.ComponentFactory<i1.LazyVirtualComponent> = i0.ɵccf('app-virtual-lazyload-component',
    i1.LazyVirtualComponent,View_LazyVirtualComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvcmFkaWNhdGUvRGV2ZWxvcG1lbnQvTGF6eUxvYWRpbmcvc3JjL2xhenktY2hpbGQuZGlyZWN0aXZlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvcmFkaWNhdGUvRGV2ZWxvcG1lbnQvTGF6eUxvYWRpbmcvc3JjL2xhenktY2hpbGQuZGlyZWN0aXZlLnRzIiwibmc6Ly8vaG9tZS9yYWRpY2F0ZS9EZXZlbG9wbWVudC9MYXp5TG9hZGluZy9zcmMvbGF6eS1jaGlsZC5kaXJlY3RpdmUudHMuTGF6eVZpcnR1YWxDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvcmFkaWNhdGUvRGV2ZWxvcG1lbnQvTGF6eUxvYWRpbmcvc3JjL2xhenktY2hpbGQuZGlyZWN0aXZlLnRzLkxhenlWaXJ0dWFsQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz0ndmlydHVhbC1lbGVtZW50Jz48L2Rpdj4iLCI8YXBwLXZpcnR1YWwtbGF6eWxvYWQtY29tcG9uZW50PjwvYXBwLXZpcnR1YWwtbGF6eWxvYWQtY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUE7TUFBQTs7O29CQ0FBO01BQUE7cUNBQUEsVUFBQTtNQUFBOzs7In0=
